### ISSUE TITLE
Lookup component hangs in Safari, must be force quit.

### ISSUE THREAD

**Issue by mford516** [ng-lightning/ng-lightning#100]
Angular 2.0.0-beta.14
ng-lightning v0.7.0
Safari 9.1.1

**What you did:** Type text in lookup and attempt to select a value.

**What you expected to happen:** Desired value to become selected.

**What actually happened:** Cursor becomes spinner and Safari browser is unresponsive, has to be force quit. I attempted to wait for an extended period of time (~14 minutes) to see it I could at least get a console error but it continued to be unresponsive.

I tested this on Safari in the component demo at http://ng-lightning.github.io/ng-lightning/ and the error is consistent. Error does not occur in Chrome, Firefox, or Microsoft Edge.

**Comment by bekos** [comment]
Hi @mford516. I tested on Mac with Safari 9.1 on our demo page and I cannot reproduce it.

Does it happen also in the plunker?

**Comment by mford516** [comment]
I spoke too soon. Cleared the browser cache and it works fine. I don't know what I had cached that would have caused that.
