### ISSUE TITLE
can not find module 'ng-lightning' installed via jspm

### ISSUE THREAD

**Issue by erashu212** [ng-lightning/ng-lightning#101]
Hi @ppolyzos ,

I am getting this error during typescript compilation "can not find module *ng-lightning*". I have installed this package via `jspm install npm:ng-lightning`.

Any help would be grateful.

**Comment by ppolyzos** [comment]
Can you try installing it using **npm** with `npm install --save ng-lightning` and check if you have the same issue? [Guide](http://ng-lightning.github.io/ng-lightning/)

Can you please give us some more details to further investigate?
- What what platform are you on? (Windows, MacOs, Linux)
- Versions of nodejs, jspm

**Comment by erashu212** [comment]
Hi @ppolyzos ,

I have tried the approach you have suggested me but no success. Here is the details for the environment I am using.

NodeJs  Version : v4.4.0
jspm Version : 0.16.32 
Os : MacOs

**Comment by bekos** [comment]
@erashu212 Did you have any luck on this? I don't know if there is much we can do here!

Closing for now, but feel free to open a new issue if you think there is something we can improve on our side.
