### ISSUE TITLE
 Error: XHR error (404 Not Found) tether

### ISSUE THREAD

**Issue by sorensl** [ng-lightning/ng-lightning#146]
Hi,

As soon as I load provideNglConfig() into my bootstrap command, I see the errors below.

My bootstrap file is quite simple:

import { bootstrap }    from '@angular/platform-browser-dynamic';
import { AppComponent } from './app.component';
import { HTTP_PROVIDERS } from '@angular/http';
import { APP_ROUTER_PROVIDERS } from './app.routes';
import {provideNglConfig} from 'ng-lightning/ng-lightning';

bootstrap(AppComponent, [ HTTP_PROVIDERS, APP_ROUTER_PROVIDERS, provideNglConfig() ]);

import { NGL_DIRECTIVES } from 'ng-lightning/ng-lightning';

This also occurs on a component if I add NGL_DIRECTIVES to the directives. 

directives: [ AppHeaderComponent, NGL_DIRECTIVES ]

In both cases, if I leave the import statements there, but take out the mentioned components, all works fine again.

login:41 Error: (SystemJS) Error: XHR error (404 Not Found) loading 
http://localhost:3000/tether(…)(anonymous function) @ login:41ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:101 GET http://localhost:3000/tether 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM35636:3fetchTextFromURL @ system.src.js:1059(anonymous function) @ system.src.js:1767ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1766(anonymous function) @ system.src.js:2795(anonymous function) @ system.src.js:3365(anonymous function) @ system.src.js:3677(anonymous function) @ system.src.js:4069(anonymous function) @ system.src.js:4532(anonymous function) @ system.src.js:4801(anonymous function) @ system.src.js:413ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426

zone.js:101 GET http://localhost:3000/tether 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM35636:3fetchTextFromURL @ system.src.js:1059(anonymous function) @ system.src.js:1767ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1766(anonymous function) @ system.src.js:2795(anonymous function) @ system.src.js:3365(anonymous function) @ system.src.js:3677(anonymous function) @ system.src.js:4069(anonymous function) @ system.src.js:4532(anonymous function) @ system.src.js:4801(anonymous function) @ system.src.js:413ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426

**Comment by sorensl** [comment]
Fix

Edit the systemjs.config.js file and add the following. You are likely to have other entries in these structures, so just add these as new lines.

```
var map = {
    'tether':                     'node_modules/tether/dist/js',
  };

var packages = {
    'tether': { main: 'tether.js', defaultExtension: 'js' },
  };

var ngPackageNames = [
    'tether',
  ];
```

**Comment by bekos** [comment]
Thanks for the info @sorensl. I will probably have to update the installation instructions to mention tether dependency and configuration also.
