### ISSUE TITLE
Need help with multiple modal windows.

### ISSUE THREAD

**Issue by Fox36rus** [ng-lightning/ng-lightning#157]
Hi,

Right now I'am working with modal windows. It's quite easy to add a single modal window.
But what about several modal windows with different body elements on a single page? 
Tried many variants and it's not working for me.
Could you show a simple example?

Thanks.

**Comment by bekos** [comment]
Hi @Fox36rus. I am not sure this is supported from LDS framework but I will look into this soon.

**Comment by bekos** [comment]
Hi again @Fox36rus. I think I misinterpreted your question yesterday, as I thought you needed to open a modal inside another. If you want your component to have more than one modals "living" inside it you can do it like this: http://plnkr.co/edit/jvaiZreyQCLsvmjAe0ku?p=preview

Does this work for you?

**Comment by Fox36rus** [comment]
Hi @bekos.
Yes, right now we understand each other and thank you very much, that perfectly worked for me!
