### ISSUE TITLE
layout and activity timeline

### ISSUE THREAD

**Issue by istiti** [ng-lightning/ng-lightning#159]
hi, I come from bootstrap design and material design, I want to change and saleforce's design, it seems clean and beautiful I hope you will fast integrate "activity timeline" for angular2, is this in your short list ? 

do you have a short list? just to see when others features will come.

ps: I'm not allowed to create new question on stackoverflow because there is not question on stackoverflow, damage 

thanks

**Comment by bekos** [comment]
Hi @istiti. We have common views about LDS :-)

We have started a [Roadmap](https://github.com/ng-lightning/ng-lightning/wiki/Roadmap) but it needs a bit refresh. Unless people start sending PRs based on their needs, the rate and the selection of new features will be based mostly on my needs. The fact is that LDS is not as popular as Bootstrap or Material design yet, and Angular 2 is still not stable, so finding people to be involved is pretty difficult.

BTW nothing stops you from using "Activity timeline" in your project now, as I see no special Javascript interactivity that you need to wait for ng-lightning to implement. If you have any suggestion though, feel free to open a new issue to discuss API, functionality etc

PS I'm aware of the SO issue, and I will try to resolve it in the next days.

**Comment by bekos** [comment]
Stackoveflow tagged has been created. See: http://stackoverflow.com/questions/tagged/ng-lightning
