### ISSUE TITLE
error tether module not resolve

### ISSUE THREAD

**Issue by istiti** [ng-lightning/ng-lightning#160]
I have this error when import and run my angular/angular2-seed app

`trigger.js:3 Uncaught Error: Cannot find module "tether"webpackMissingModule @ trigger.js:3(anonymous function) @ trigger.js:3__webpack_require__ @ bootstrap c18197d…:50(anonymous function) @ directives.js:3__webpack_require__ @ bootstrap c18197d…:50(anonymous function) @ ng-lightning.js:28__webpack_require__ @ bootstrap c18197d…:50(anonymous function) @ app.ts:4__webpack_require__ @ bootstrap c18197d…:50(anonymous function) @ main.browser.ts:7__webpack_require__ @ bootstrap c18197d…:50(anonymous function) @ main.bundle.js:6__webpack_require__ @ bootstrap c18197d…:50webpackJsonpCallback @ bootstrap c18197d…:21(anonymous function) @ main.bundle.js:1
client:45 [WDS] Errors while compiling.
client:47 ./~/ng-lightning/popovers/trigger.js
Module not found: Error: Cannot resolve module 'tether' in C:\Users\e.begovic\WebstormProjects\ng2seed\angular2-seed\node_modules\ng-lightning\popovers`

**Comment by bekos** [comment]
Have you installed tether? This is a peer dependency for popovers/tooltips to work.
Check it out here: https://www.npmjs.com/package/tether and tell me if this works for you.

**Comment by istiti** [comment]
ok problem is in npm install I thinked your ng-ligthning are including It will installed it to me automatically, but it won't but OK problem solved after isntall tether manually, another simple/basic question: the css style  of SLDS  isn't included in this ng-ligthnin module ? Because no css style applied, I have to  put it manually in my index.html ?

**Comment by bekos** [comment]
Yes, your `npm` script script should have warned about an unmet peer dependency, but I think we should document it better :(

That's true, you should include the CSS framework yourself either from the SASS source files or their minified/bundled version. It's your choice. BTW you can see the source of our demo page in case that helps.

**Comment by istiti** [comment]
very appreciate the reactivity, thanks a lot... yes I won't clone your github repo with demo because there is a lot options and I'm new to angular2, your repo is certainely very clear I believe it but i'm new to ng2 and it seems me confusing ...

As now I start with angular2-seed and I try to add in the good way  the SLDS style to my webapp, until know I have no style effect because in my root component I don't specify the styleUrls to the SDLS css, because the path is in node_modules.

It's envisageable to add the SDLS style css into your lib, like this we won't worry about the salesforce's npm repo 

cheers

**Comment by bekos** [comment]
@istiti Thx and I'm happy you found the solution 👍  

Closing as this is not an issue with our codebase.
