### ISSUE TITLE
1 millions rows (virtual scroll) 

### ISSUE THREAD

**Issue by istiti** [ng-lightning/ng-lightning#164]
It's envisageable to implement something like this must-have feature  in your datatable ? https://developers.google.com/web/updates/2016/07/infinite-scroller

I think nowadays we manipulate a large set of data and we are led to manipulate that better/faster DOM recycling  technic may be good approach , so let me  know if you can have this in your vision

thx

**Comment by bekos** [comment]
Hi @istiti. I agree with you, that this is needed in large datatables if you don't have paging, but I am not sure this should be implemented as part of this library. There are/will be a lot standalone modules for angular 2 that will implement virtual scrolling.

We just need to provide an easy way for you to integrate them, but we should wait to see what tools/methods  Angular's core team will provide us :-)

Closing, as this is not actionable atm. Thanks for your feedback.
