### ISSUE TITLE
Customizing modal window

### ISSUE THREAD

**Issue by Fox36rus** [ng-lightning/ng-lightning#166]
Hello,

Still working on modal windows and right now can't figure out how to make a custom window.
It would be awesome if you could help.
1) Is there only 3 size of modal windows? Is it possible to make a custom size?
Tried to put different value into size but without succeed.
2)Structure of the modal windows is permanent? With  3 elements like header, body, and footer it looks strange when i just don't want to have header but it still there.
By the way, is it possible to change font-size or style of the header?
3)Buttons on the bottom. For example - I need "back" and "next" buttons and obviously put them in opposite sides of the modal window. It's a little complicated.

Thank you very much for your hard work. Hope to hear from u soon.

**Comment by bekos** [comment]
Hi @Fox36rus :-)

This library is just the Javascript functionality for what the LDS HTML/CSS provides. Regarding your size question you should see [here](https://www.lightningdesignsystem.com/components/modals/) for what is available.

We will soon implement modals without header or footer, and directional buttons (hint: this is an easy PR) but everything related to font family, size etc you have to provide the appropriate CSS override rules.

BTW, this is more like a support question, and I would highly appreciate if you were using Stackoverflow, http://stackoverflow.com/questions/ask?tags=ng-lightning, so it's easier for other to find the answers to similar questions. Thx.

Leaving open as reminder for directional buttons and modal with no header/footer.

**Comment by bekos** [comment]
Empty header and directional footer is already fixed in master via 723b563db2a59377605158aa06458a02d405ea43 and 6bf0d2d4105dd7379ab51e6398eb551831ddfe17 respectively, and will be part of the next release.

I have opened #173 to tackle the no footer issue.
