### ISSUE TITLE
(feat): Custom language for datepicker

### ISSUE THREAD

**Issue by egabe** [ng-lightning/ng-lightning#176]
Hello!

Is it possible to set custom language (for month) in datepicker?

**Comment by bekos** [comment]
Hi @egabe. This is not something we support atm, but it's definitely in our roadmap.
I'm waiting for Angular i18n solution in order to decide how to tackle it.

**Comment by egabe** [comment]
Okay. I see. Thank you.

**Comment by bekos** [comment]
@egabe Since 0.19 you can provide `[monthNames]` as input to your datepicker component. Hope this solves your issue.

**Comment by egabe** [comment]
Thank you.
