### ISSUE TITLE
Datepicker: support for disabled dates

### ISSUE THREAD

**Issue by ciesielskico** [ng-lightning/ng-lightning#186]
Hi, thanks for your awesome components. 

One thing I am missing with the datepicker is the ability to disable specific dates, e.g
`['21.12.2012', '22.12.2012']`

but also to disable dates before a certain date, e.g. disable all dates before 'today'.

Cheers!

**Comment by bekos** [comment]
Hi @ciesielskico. This is certainly something we want to implement. Keeping open in order to track.

**Comment by bekos** [comment]
It will be supported on next release via bf0606892203eb5ea7daf43250037ebe3c863ab7.
