### ISSUE TITLE
Support for white icons

### ISSUE THREAD

**Issue by clozanosanchez** [ng-lightning/ng-lightning#190]
Regarding Lightning Design System, icons are white by default. Then, as a user, you can change the color using the following classes: 
- .slds-icon-text-default: same as default text
- .slds-icon-text-warning: yellow
- .slds-icon-text-error: red

The problem is that ngl-icon component sets by default the class .slds-icon-text-default. So, there is no possibility to use white icons. 

A possible solution is to force users to use the attribute type="default" if they want to add .slds-icon-text-default. In this case, if the user does not fill the type attribute, then the icon is white. 

Another possible solution is to add a new type 'white' in order that users can choose white icons. In this case, if users choose type='white', the .slds-icon-text-default is not added.

**Comment by bekos** [comment]
@clozanosanchez I see. Although it will be a breaking change, I believe not defaulting `type` to `default` is the best option here. Otherwise, providing our own custom value, like `white`, may be unpleasantly surprising for the users. What do you think?

**Comment by clozanosanchez** [comment]
I agree that the best option is not defaulting type to default. For me this option is the correct one. The alternative prevents a breaking change, but on long term it is not the best one. 

If you wish, I can implement it together with my other two patches when I have some free time.

**Comment by bekos** [comment]
Agree. Looking forward to your PRs :-)
