### ISSUE TITLE
ng-lightning does not work with rc6?(works with rc5 though)

### ISSUE THREAD

**Issue by reddead** [ng-lightning/ng-lightning#192]
found this issue rencently,

Error: TypeError: core_1.provide is not a function
at Object.provideNglConfig (https://npmcdn.com/ng-lightning@0.19.0/ng-lightning.bundle.js:3753:24)

**Comment by bekos** [comment]
@reddead Today 0.20 was released with rc6 support. Can you test it?

**Comment by bekos** [comment]
Closing since 0.20 seems to work with rc6.
Feel free to reopen if you find anything else.
