### ISSUE TITLE
Where should I put some documentation?

### ISSUE THREAD

**Issue by osdamv** [ng-lightning/ng-lightning#212]
I am a little noob with angular2, for example the installation documentation doesn't mention anything about the need of add the '@salesforce-ux/design-system' to the project, by npm or the style tag.

I would love make some documentation about that but where?

**Comment by bekos** [comment]
Hi @osdamv and thx for your willingness to improve the documentation :-)
Installation & Usage instructions can be found either on the [README](https://github.com/ng-lightning/ng-lightning/blob/master/README.md) or on our [intro page](https://github.com/ng-lightning/ng-lightning/blob/master/demo/components/intro/intro.jade) of the demo site.

I hope this helps and if you have suggestions about our demo structure, I would to hear them. Closing and waiting your PR ;-)

**Comment by sstorie** [comment]
Just some thoughts as a newcomer to this library...it's not clear to me at all how to get the styles shown in the demos to work. I'm using webpack to compile all my code, and it runs without any errors from Angular (so I think ng-lightning is loading and running fine) but a simple attempt at using a button just looks stock. I manually added the stylesheet from the @salesforce-ux library, but that doesn't have any effect either.

Here's what Chrome is showing me in the debug tools:

```
<button nglbutton="neutral" type="button" ng-reflect-disabled="true" disabled="">
                Save configuration
            </button>
```

So again, the directive is there, but seems like nothing is actually happening.

**Comment by bekos** [comment]
Hi @sstorie and thx for using ng-lightning.
Please don't comment on closed issues, since it's difficult to track.

I am not sure what your actual problem is without seeing actual code, but you can see an example implementation both in our plunkers and in our demo (using webpack).

Please open a new issue/PR if you think there is anything we can improve on our side.
