### ISSUE TITLE
datepicker on input

### ISSUE THREAD

**Issue by denkomanceski** [ng-lightning/ng-lightning#227]
Is there any way how to put the datepicker as a directive on an input so it will be shown when the user focuses that input ? Since displaying just the datepicker straight on the page does not have many usecases right ?
Something like: https://www.youtube.com/watch?v=UZtvQazYX8A - 2:03
Regards

**Comment by clozanosanchez** [comment]
As far as I know, it does not possible to put the datepicker as a directive for the moment. In my case, I have used the following workaround to solve the same problem:

```
<div class="slds-form-element">
    <label class="slds-form-element__label" for="date">Date</label>
    <div class="slds-form-element__control slds-input-has-icon slds-input-has-icon--right">
        <div nglDropdown [(open)]="openNglDatepicker" class="slds-input">
            <div nglDropdownTrigger>
                <span>{{DATE_MODEL | date:'dd/MM/yy'}}</span>
                <ngl-icon category="utility" icon="event" size="x-small" svgClass="slds-input__icon"></ngl-icon>
            </div>
            <div class="slds-dropdown slds-dropdown--left">
                <ngl-datepicker nglDropdownItem [date]="DATE_MODEL" (dateChange)="DATE_MODEL = $event; openNglDatepicker = false" class="slds-box slds-box--x-small"></ngl-datepicker>
            </div>
        </div>
    </div>
</div>
```

**Comment by bekos** [comment]
As @clozanosanchez said, this not something we support at the moment, but I think you can easily achieve it by placing the datepicker inside a dropodown (as @clozanosanchez  example) or inside a popover. Anyway this is something we want to support in the future, so Im leaving open to track it.

**Comment by esarbanis** [comment]
This will be implemented once we upgrade slds dependency to 2.5.0 as part of the [new datepicker component](https://www.lightningdesignsystem.com/components/datetime-picker).

Hope this will be soon :slightly_smiling_face:

**Comment by m4rs2k** [comment]
do you think the upgrade will be finished this year?

**Comment by bekos** [comment]
It will be supported on next release via 1137b99115bf990a3d4c5a26c9245f03212a14b1.
