### ISSUE TITLE
systemjs

### ISSUE THREAD

**Issue by egabe** [ng-lightning/ng-lightning#230]
Hello!

I'd like to use ng-lightning with system js (as in the official angular2 document), but I can't find the right way to import ng-lightning in this new angular 2.0.0, NgModule formula. Somebody could send me a working example? I use the standard systemjs config from the official document.

**Comment by bekos** [comment]
Hi @egabe and thx for using ng-lightning! Take a look at one of our Plunker demos. There we use SystemJS. Give it a try and reopen if you still have issues.
