### ISSUE TITLE
Template Parse error when using some form elements

### ISSUE THREAD

**Issue by Chyngyz** [ng-lightning/ng-lightning#242]
I get `Unhandled Promise rejection: Template parse errors:` only when I use these form elements:  **ngl-form-checkbox**, **ngl-form-group-element**. All other components works fine. 

Angular version: 2.0.1
Boilerplate: https://github.com/preboot/angular2-webpack

**Comment by bekos** [comment]
Hi @Chyngyz. Can you make sure that you are using the latest version? (0.24.0)
Also, you now have to add `nglFormControl` to your checkbox element.

**Comment by Chyngyz** [comment]
Hi @bekos, thanks for quick reply. I updated to the latest version, and now I have 
`Uncaught SyntaxError: Unexpected token import -  ng-lightning.js?88d3:1`. In my template I use like this: 

```js
<ngl-form-checkbox label="Checkbox Label">
  <input nglFormControl type="checkbox" />
</ngl-form-element>
```

**Comment by bekos** [comment]
I think this is due to the fact that we are now shipping ES 2015 modules and this works only with webpack 2. This starter is already using webpack 2, can you confirm you are up to date?

**Comment by Chyngyz** [comment]
@bekos Thanks for lightning fast replies :+1:  Uuuhh, I am not up to date, let me update and see if everything will be ok. Thanks a lot.

**Comment by Chyngyz** [comment]
@bekos Updating to webpack 2 solved the issue, thank you very much for help. Closing.

**Comment by bekos** [comment]
@Chyngyz Thanks for using ng-lightning. Glad you solved it 👍
