### ISSUE TITLE
Datepicker: choose first day of week

### ISSUE THREAD

**Issue by sdiprizio** [ng-lightning/ng-lightning#252]
Hi,

It would be great to be able to define the first day of the week (sunday in US but monday in many countries).
BTW thanks for this great library.
Regards.

Stéphane

**Comment by bekos** [comment]
Hi @sdiprizio and thanks for your kind words. This is definitely in our roadmap, but not a high priority atm. That said, I believe this could be a good change for a PR :-)

**Comment by sdiprizio** [comment]
Done :)
See pull request #255
