### ISSUE TITLE
 Cannot find type definition file for 'core-js'

### ISSUE THREAD

**Issue by jerry-i** [ng-lightning/ng-lightning#265]
ng-lightning@1.0.0
angular@2.1.2
build with webpack;
typing with npm  like `@types/node`
webpack compile error;
```
xxx/node_modules/ng-lightning/config/config.d.ts:1:1
    Cannot find type definition file for 'core-js'
```

**Comment by bekos** [comment]
You can use `@types/core-js`. Install it using `npm install --save-dev @types/core-js`.

**Comment by pulsar256** [comment]
@bekos: doing that on project level results in:
"...node_modules/@types/core-js/index.d.ts:21:13 
Duplicate identifier 'PropertyKey'."

**Comment by pulsar256** [comment]
removing `///<reference types="core-js" />` from `config.d.ts` helps as a workaround

**Comment by bekos** [comment]
Can this issue be related? https://github.com/angular/in-memory-web-api/issues/62

**Comment by pulsar256** [comment]
I have upgraded ng-cli and ngl at the same time so it is more than likely to be related. I will downgrade the cli to .18 and let you know.

**Comment by pulsar256** [comment]
Downgrading to 0.27.0 helps too.

**Comment by bekos** [comment]
I believe removing `@types/core-js` from `ng-lightning` will fix this. I will make a new release soon.

**Comment by bekos** [comment]
@jerry-i @pulsar256 v1.0.1 has just been released. I would appreciate if you confirm that everything works :-)

**Comment by jerry-i** [comment]
@bekos THX😝

**Comment by pulsar256** [comment]
@bekos 1.0.1 works fine, thanks!
