### ISSUE TITLE
Lookup not closed after value is selected

### ISSUE THREAD

**Issue by charlieamer** [ng-lightning/ng-lightning#266]
Hello

I am trying to make a profile setup page on my website, and I stumbled upon a small problem. User has ability to select multiple languages, and I decided to use lookup for that. However, problem rises if I decide NOT to use two-way data binding like we usually do. Instead I just subscribe to (pickupChange).
```html
<ngl-lookup (pickChange)="value = $event" field="name" [lookup]="lookup">
</ngl-lookup>
```
When I select an item, pickChange event is fired successfuly, but, the lookup menu is not closed, it stays open. It would be nice if it closed after being selected.

**Comment by bekos** [comment]
hi @charlieamer. A solution would be to export lookup's open/close methods so people can use them. You can send a PR if you want, otherwise I will work on it, next week.

**Comment by charlieamer** [comment]
Hi, thank you for response. There is already exported function, i didn't realize. I managed to do what I wanted by doing the following:
```html
<ngl-lookup (pickChange)="value = $event" field="name" [lookup]="lookup" [pick]="null">
</ngl-lookup>
```
*Notice the pick property = null*

Now when I say element.open = false in typescript, the lookup closes as expected. Thank you and sorry for bothering.
