### ISSUE TITLE
Datatable on dataTrackBy

### ISSUE THREAD

**Issue by chinaxy** [ng-lightning/ng-lightning#268]
[version]
angular: 2.1.2 & 2.2.0
ng-lightning: 1.0.0 & 1.0.1

[bug]
The function 'dataTrackBy' is not running correctly, the 'this' variable is a 'DefaultIterableDiffer', not a 'NglDatatable'

**Comment by bekos** [comment]
Hi @chinaxy. Can you provide a minimal reproduce scenario using our Plunker buttons? It's very difficult to understand what's going wrong without it. Thx.

**Comment by chinaxy** [comment]
Without modifying the source code, it is difficult to explain the problem.
I provide an idea to reproduce the problem, see this 
https://plnkr.co/edit/kBNUKe4sdfBomze1Pk4y?p=preview
When we open the debug mode, it is clear that 'this' is a 'DefaultIterableDiffer', rather than the current object

**Comment by bekos** [comment]
I'm not sure I understand your case but `ng-lightning`'s datatable `trackByKey` should be a string value, not a function. This string should be a property that uniquely identifies each record of your data. Do you pass a function in `trackByKey`? Your plunker is not using `ngl-datatable`, just a plain `ngFor`. Can you elaborate?

**Comment by chinaxy** [comment]
The method 'dataTrackBy (index: number, data: any)' is used to identify a data in the source file 'src\ datatables\datatable.ts', but in the body of the method, 'this.trackByKey' 'this' is no longer an instance of the current object 'NglDatatable', but rather an 'angular' built-in object

**Comment by bekos** [comment]
Oh, now I see! Thank you very much for this, you are absolutely right.
I am not sure how to test this, but I will send a fix soon. Thx again 👍
