### ISSUE TITLE
ngl-icon throws 'TypeError: Cannot read property 'unsubscribe' of undefined' in ngSwitchDefault

### ISSUE THREAD

**Issue by evan-yudha** [ng-lightning/ng-lightning#270]
Angular version: 2.1.2
ng-lightning version: 1.0.0

Hi first issue I reported here. Hope I'm doing this right; couldn't produce a plunker, not familiar with it if anymore complex than adding js libs..

I have a dynamic sidebar populated with tree of nodes with template like this:

    <nav>
      <ul>
      <template ngFor let-node [ngForOf]="menu">
        <li [ngSwitch]="node.isLeaf"
            [class.is-closed]="node.isCollapsed"
            [class.sidebar__has-children]="!node.isLeaf">
          <ng-container *ngSwitchCase="true">
            <a [routerLink]="node.route">
              <span>
                <ngl-icon [icon]="node.icon[0]" [category]="node.icon[1]"></ngl-icon>
                <span>{{node.label}}</span>
              </span>
            </a>
          </ng-container>
          <ng-container *ngSwitchCase="false">
          
            <a (click)="node.toggle()">
              <span>
                <ngl-icon [icon]="node.icon[0]" [category]="node.icon[1]"></ngl-icon>
                <span>{{node.label}}</span>
                <ngl-icon svgClass="chevron" size="small" [icon]="node.isCollapsed ? 'right' : 'down'"></ngl-icon>
              </span>
            </a>
            <ul>
              <li *ngFor="let child of node.children;">
                <a [routerLink]="child.route">
                  <span>{{child.label}}</span>
                </a>
              </li>
            </ul>
          </ng-container>
        </li>
      </template>
      </ul>
    </nav>

It was working until 0.27.0, upgrading to 1.0.0 starts throwing TypeError: Cannot read property 'unsubscribe' of undefined, coming from nglIconSvg.onDestroy

ngSwitchCase or ngIf works fine. Just ngSwitchDefault.
I'd love to do more digging if if it looks like a quick fix isn't obvious..
Thanks

**Comment by bekos** [comment]
@evan-yudha I am not sure I understand why this happens, but I have applied a fix to prevent these kind of errors. I will make a patch release soon.
