### ISSUE TITLE
refresh datatable 

### ISSUE THREAD

**Issue by chinaxy** [ng-lightning/ng-lightning#272]
[version]
angular: 2.2.1
ng-lightning: 1.0.2

https://plnkr.co/edit/xySSc1lEwxP3Fx0PQaPZ?p=preview

After the table rendering is complete, I modified the data, but the table is not updated, whether there is a corresponding method to refresh the display?

**Comment by bekos** [comment]
Hi @chinaxy and thx for your feedback :-)
For performance reasons we choose to use `OnPush` change detection, so you have to make a new object each time you want to alter on of your rows.

See here: https://plnkr.co/edit/6BI28mjVfeSuzg1GeNzq?p=preview
Does this make sense?

**Comment by bekos** [comment]
Probably we need to document this on our demo site. I will happily accept a PR for this :-)

**Comment by chinaxy** [comment]
I understand, thank you, please close the PR.

**Comment by bekos** [comment]
👍
