### ISSUE TITLE
Change name of lib

### ISSUE THREAD

**Issue by istiti** [ng-lightning/ng-lightning#277]
Calling lib with ng- prefix is anti pattern cause it's reserved for core directives.
It's not mandatory but angular team recommend use your own prefix, ideas:
[your_abbreviation_name]-lightning
[your_abbreviation_society]-lightning
The-lightning
...

**Comment by bekos** [comment]
All our components and directives are prefixed with `ngl`, notice the `l` in the end.
So we follow angular team's recommendation and there is no way we will ever conflict with any core component.

The name of the library is totally irrelevant, but thx for pointing this out though  :-)
