### ISSUE TITLE
starter kit

### ISSUE THREAD

**Issue by istiti** [ng-lightning/ng-lightning#278]
ENHANCEMENT: 
Do you planed have something like layout component.... a starter kit .... which make time to make but very very relevant for new developer who want try this awesome design, something like : 
https://github.com/salesforce-ux/design-system-starter-kit

e.g. https://starter-kit-demo.herokuapp.com/example.html

Cheers

**Comment by bekos** [comment]
This is not the purpose of this this library, but I suppose it will tremendously help new developers to get started with `ng-lightning` and SLDS in general. Leaving open until we decide what is the best thing to do here. Thx for your proposal :-)

**Comment by bekos** [comment]
This is not in our plans right now. If anyone is interested to implement it, can send a PR.
