### ISSUE TITLE
Picklist inside Modals body 

### ISSUE THREAD

**Issue by denkomanceski** [ng-lightning/ng-lightning#279]
I have a picklist inside of a modal: http://prntscr.com/ddjyw9. The scrolling in the picklist doesnt work. Instead, it scrolls the page in background. Also, when I remove the custom height for the body (http://prntscr.com/ddjzc5), the picklist dropdown is almost impossible to see with the default overflow-y: auto settings, but when setting it to visible, the dropdown is shown but I cannot scroll it. Any solution for this ? This is how it looks in bootstrap (http://prntscr.com/ddk0ad) and I want to recreate the same functionality with ng-lightning

**Comment by bekos** [comment]
Hi @denkomanceski. Can you setup a plunker with your issue? This will help us investigate and probably help with your issue. You can start by using the `Try in Plunker` button in our demo site.

**Comment by denkomanceski** [comment]
Here it is: https://plnkr.co/edit/qEYofegYe3EKcPGaz7ED?p=preview
It is hard to actually choose something, the list should go over the modal I guess, but if I make it go over the modal, the scroll doesnt work.. it scrolls the page behind the modal

**Comment by bekos** [comment]
This is a CSS problem, and you should definitely raise it at [SLDS repo](https://github.com/salesforce-ux/design-system/issues). That being said, I will try to think of a workaround, as this seems like a common use case that needs to be handled.

**Comment by denkomanceski** [comment]
@bekos Any idea for a workaround on this?

**Comment by bekos** [comment]
Until a proper fix/workaround, you can probably use a popover instead of dropdown, or apply on your side the CSS rules related to overflow.

**Comment by bekos** [comment]
This is fixed via f4aa1b20effeeacf3296b64799090be1c73067a6.
