### ISSUE TITLE
Disabling a tab

### ISSUE THREAD

**Issue by denkomanceski** [ng-lightning/ng-lightning#280]
Is it possible to make a tab disabled? [disabled] doesnt work, I checked in the source code, it seems its not currently possible right ?

**Comment by bekos** [comment]
There is no CSS class for disabled tab in SLDS so you have to implelement your own, but the javascript part can be achieved by utilising the `selectedChange` event with your own custom logic.

See a simple example here: https://plnkr.co/edit/1yTR7Ginh2LDmyiZxzGX?p=preview

Does this work for you?

**Comment by denkomanceski** [comment]
Ye, this would work fine for now thanks. My case was: based on some checkboxes some tab is disabled/enabled. ty
