### ISSUE TITLE
Package can't be loaded with JSPM

### ISSUE THREAD

**Issue by DaSchTour** [ng-lightning/ng-lightning#283]
When trying to use JSPM I get error telling me "Unexpected keyword 'import'".
Looks like the "bundle" isn't made for direct usage or something is missing in distribution :(

It could be so easy.

Please add a barrel index.ts to root and reexport src and everything will work fine with commonjs, SystemJS and NPM. Import can than simply be done through `import {...} from "ng-lightning"`

**Comment by bekos** [comment]
Hi @DaSchTour. Do you map `ng-lightning` to our bundle file?

Something like this:
```js
map: { 'ng-lightning/ng-lightning': 'node_modules/ng-lightning/bundles/ng-lightning.umd.js' }
```

**Comment by DaSchTour** [comment]
My config is created through JSPM so I don't touch it. But in fact `import {...} from "ng-lightning"` already works correctly when using JSPM and TypeScript even recognizes the package correctly. So there is no need for changing the generated systemjs config and documentation is just wrong.

**Comment by bekos** [comment]
You should import  from "ng-lightning/ng-lightning", not just "ng-lightning".

**Comment by DaSchTour** [comment]
Well but the package isn't bundled correctly for using "ng-lightning/ng-lightning", this import would use the raw src JS and not the bundle. JSPM already links the correct "ng-lightning/bundles/ng-lightning.umd.js" for "ng-lightning" package. I just thought, that typescript node module resolution will not work that way. But since typings in package.json are referenced correctly TypeScript understands that import from "ng-lightning" is exactly the same as "ng-lightning/ng-lightning".
