### ISSUE TITLE
ctorParameters.map is not a function

### ISSUE THREAD

**Issue by Jarvens** [ng-lightning/ng-lightning#287]
Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:3001/vendor.js:39305:45)
    at Reflector.parameters (http://localhost:3001/vendor.js:39439:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:3001/vendor.js:22157:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:3001/vendor.js:22122:26)
    at http://localhost:3001/vendor.js:22265:41
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (http://localhost:3001/vendor.js:22245:19)
    at http://localhost:3001/vendor.js:21943:71
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3001/vendor.js:21934:44)
    at RuntimeCompiler._compileComponents (http://localhost:3001/vendor.js:33933:47)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:3001/vendor.js:33871:37)
    at RuntimeCompiler.compileModuleAsync (http://localhost:3001/vendor.js:33862:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3001/vendor.js:24116:25)
    at PlatformRef_.bootstrapModule (http://localhost:3001/vendor.js:24098:21)
    at Object.<anonymous> (http://localhost:3001/main.js:34495:6)
    at __webpack_require__ (http://localhost:3001/polyfills.js:53:30)
    at Object.<anonymous> (http://localhost:3001/main.js:54223:18)
    at __webpack_require__ (http://localhost:3001/polyfills.js:53:30)
    at webpackJsonpCallback (http://localhost:3001/polyfills.js:24:23)
    at http://localhost:3001/main.js:1:1

this  is my package json

"dependencies": {
    "@angular/common": "~2.1.2",
    "@angular/compiler": "~2.1.2",
    "@angular/core": "~2.1.2",
    "@angular/forms": "~2.1.2",
    "@angular/http": "~2.1.2",
    "@angular/platform-browser": "~2.1.2",
    "@angular/platform-browser-dynamic": "~2.1.2",
    "@angular/router": "~3.1.2",
    "core-js": "^2.4.1",
    "lodash": "^4.16.4",
    "md5-hex": "^1.1.0",
    "moment": "^2.12.0",
    "ng-lightning": "^1.2.0",
    "ng2-bootstrap": "^1.1.16",
    "pluralize": "~3.0.0",
    "rxjs": "5.0.0-beta.12",
    "time-ago": "^0.1.0",
    "toastr": "^2.1.2",
    "zone.js": "~0.6.17"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.35",
    "@types/lodash": "^4.14.37",
    "@types/node": "^6.0.45",
    "@types/pluralize": "0.0.27",
    "@types/source-map": "^0.1.28",
    "@types/toastr": "^2.1.27",
    "@types/webpack": "^1.12.35",
    "angular2-template-loader": "^0.5.0",
    "angular2-router-loader": "^0.3.4",
    "awesome-typescript-loader": "^2.2.4",
    "codelyzer": "~1.0.0-beta.0",
    "css-loader": "^0.25.0",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "file-loader": "^0.9.0",
    "html-minify-loader": "^1.1.0",
    "html-webpack-plugin": "ampedandwired/html-webpack-plugin",
    "imports-loader": "^0.6.5",
    "jquery": "^3.1.1",
    "raw-loader": "^0.5.1",
    "resolve-url-loader": "~1.6.0",
    "rimraf": "2.5.4",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.0",
    "ts-helpers": "^1.1.1",
    "tslint": "^3.15.1",
    "tslint-loader": "^2.1.3",
    "typescript": "^2.0.3",
    "url-loader": "^0.5.7",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-server": "^2.1.0-beta.7",
    "webpack-manifest-plugin": "^1.0.0",
    "webpack-merge": "~0.14.1"
  }
}

this is my appModule

@NgModule({
  bootstrap: [AppComponent],
  declarations: [
    AppComponent,
    NoContentComponent,
    Navbar, AddressMenu,
    Index
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(ROUTES),
    Ng2BootstrapModule,
    NglModule.forRoot(),
    HttpModule
  ],
  providers: [
    ENV_PROVIDERS,MyHttp
  ]
})
export class AppModule {
}

someone can help me ?

**Comment by bekos** [comment]
@Jarvens Can you tell me which components you use? As you understand it is very difficult for us to help you, without a minimal reproduce scenario.

**Comment by Jarvens** [comment]
this is my use lightning place

import {NgModule} from "@angular/core";
import {BrowserModule} from "@angular/platform-browser";
import {RouterModule} from "@angular/router";
import {ENV_PROVIDERS} from "./environment";
import {ROUTES} from "./app.routes";
import {AppComponent} from "./app.component";
import {NoContentComponent} from "./page/no-content.component";
import {Ng2BootstrapModule} from "ng2-bootstrap/ng2-bootstrap";
import {Index} from "./page/index/index.comp";
import {AddressMenu} from "./page/index/addressmenu/addressmenu";
import {Navbar} from "./page/index/navbar";
import {MyHttp} from "./core/http/http";
import {HttpModule} from "@angular/http";
import {NglModule} from "ng-lightning";

@NgModule({
  imports: [
    BrowserModule,
    RouterModule.forRoot(ROUTES),
    Ng2BootstrapModule,
    HttpModule,
    NglModule.forRoot()
    //nUserModule,
    //IndexModule,
    //EditorModule
  ],
  declarations: [
    AppComponent,
    NoContentComponent,
    Navbar, AddressMenu,
    Index
  ],
  bootstrap: [AppComponent],
  providers: [
    ENV_PROVIDERS,MyHttp
  ]
})
export class AppModule {
}

**Comment by bekos** [comment]
One thing I notice is that you should import from **'ng-lightning/ng-lightning'** instead of just 'ng-lightning', but I don't know if this is the issue here.

**Comment by Jarvens** [comment]
there still a mistake .but  when i use system.js  loader ng-lightning  it worked succeful

**Comment by Jarvens** [comment]
i don't konw how to resolve this mistake

**Comment by bekos** [comment]
I am afraid that I cannot help either with the information we got. Try to make a plunker.

**Comment by Jarvens** [comment]
OK,thank you
