### ISSUE TITLE
updating table

### ISSUE THREAD

**Issue by denkomanceski** [ng-lightning/ng-lightning#288]
How to update a table? When I add new item to the supplied list,  I have to destroy and create the table for the changes to reflect. Any workaround ?

**Comment by bekos** [comment]
You have to create a new object for the updated row. See here: https://plnkr.co/edit/6BI28mjVfeSuzg1GeNzq?p=preview

**Comment by bekos** [comment]
If you want to add...you can create a new array like this: https://plnkr.co/edit/1QDpu1O6wjlcFO9VZRgI?p=preview

**Comment by bekos** [comment]
If you think this something we can do on our side, please feel free to reopen.

**Comment by denkomanceski** [comment]
@bekos Thanks, but I dont want to add a row, and I dont want to track which row the user changed. I just want to completely refresh the array. I modified that plunkr that you sent: https://plnkr.co/edit/O6Q1nNRfcphhNinL37F6?p=preview
