### ISSUE TITLE
Error installing ng-lightning 

### ISSUE THREAD

**Issue by JoeyOgalesco** [ng-lightning/ng-lightning#290]
Error installing ng-lightning under administrator. 

$ npm install --save ng-lightning
npm WARN saveError ENOENT: no such file or directory

**Comment by bekos** [comment]
@JoeyOgalesco I don't think we can be of much help, based on the limited info you provide. Can you give any more details?

**Comment by DaSchTour** [comment]
@JoeyOgalesco looks like you have no `package.json` in your project. You can create one with `npm init`. After the init `npm install --save ng-lightning` will work.

**Comment by bekos** [comment]
@JoeyOgalesco Did @DaSchTour comment helped? Let's close this issue for now, but feel free open to reopen in case you need any more help.
