### ISSUE TITLE
How can you use ng-lightning with an angular 2 webpack project

### ISSUE THREAD

**Issue by joelmuskwe** [ng-lightning/ng-lightning#297]
Need assistance on how to import ng-lightning in an angular 2 webpack project

**Comment by bekos** [comment]
@joelmuskwe You can investigate our demo project [here](https://github.com/ng-lightning/ng-lightning/tree/master/demo) which uses webpack. Usually just following the instructions here: http://ng-lightning.github.io/ng-lightning/ is enough.

Does this help?

**Comment by joelmuskwe** [comment]
the challenge i am facing is that my project uses a vendor.ts so i'm not sure if i add any references in it or it just suffices to an html-loader and add { test: /\.md$/, loader: 'html-loader?minimize=false!markdown-loader'  to my webpack.config.js

**Comment by bekos** [comment]
I am not sure I understand your problem. Can u elaborate?
