### ISSUE TITLE
Where is the Tree Grid component?

### ISSUE THREAD

**Issue by askarhu** [ng-lightning/ng-lightning#298]
Thank you so much for putting this together. Lightning Design is so cool and having an ng version of it only makes it look even cooler.

Everything looks great, except when I looked for a Tree Grid ng component, is it supported? Where can I find one that I can use? I'm still learning to walk in Angular2 and can't take that task on my own. Can you please share your thoughts of whether it's supported, going to be supported, or where else can I find one that I can use?

Appreciate your help and for bringing this library up.

**Comment by bekos** [comment]
There is an open PR #49 about trees, but it's not finished yet, nor it's going to be finished any time soon ;)
Until that day... https://github.com/500tech/angular2-tree-component seems like a good alternative.
