### ISSUE TITLE
datatable support header class

### ISSUE THREAD

**Issue by roblacy** [ng-lightning/ng-lightning#299]
What I really want to do is configure a fixed-layout datatable with variable width columns. One clear way to do this is to give a width to each `<th>` element. I tried assigning widths to the `<td>` elements using the `cellClass` attribute, but it did not work. Could you add support for a headerClass attribute maybe? Or is there another way? For now I'm setting `<th>` widths with my global styles.scss using nth-child, but it would be great to do this within the table code. Thanks!

**Comment by bekos** [comment]
@roblacy Thx for using ng-lightning and sorry for the delayed response. This is something we could easily support, and sounds very reasonable to do so ;) I hope to implement this soon, in the meantime feel free to send a PR if you want!

**Comment by bekos** [comment]
You can now use `headClass` same as `ngClass`, in your `<ngl-datatable-column>`.
Hope this works for you!
