### ISSUE TITLE
Icons in plunkers not being rendered

### ISSUE THREAD

**Issue by wgerven** [ng-lightning/ng-lightning#301]
When I go to any of your example plunkers which contain icons (like buttons, avatars, images, ...) they are not being rendered. E.g.,
![screenshot_2017-01-24_19-14-31](https://cloud.githubusercontent.com/assets/20610101/22260387/5dab8376-e269-11e6-84f4-1ce6e814f3cc.png)
(while on your components page they are visible.)

I have the same issue as your plunks appear to show with my setup (I'm at angular v2.4.4 and lighting v1.2.0). Components are being rendered correctly, but apparently image files for the icons are not being loaded. 

How would I be able to resolve this issue?

**Comment by wgerven** [comment]
I came back to this problem, and actually solved it by using 
`new CopyWebpackPlugin([
      { from: path.resolve(__dirname, '../node_modules/@salesforce-ux/design-system/assets'), to: 'assets' }
]),`
in my webpack config, inspired by your demo config. 

This issue can be closed. Thanks for the great work!

**Comment by bekos** [comment]
👍
