### ISSUE TITLE
Datatable with striped rows and fixed layout causes text to be displayed over each other on white rows

### ISSUE THREAD

**Issue by Nelsch** [ng-lightning/ng-lightning#302]
When using a datatable with striped rows and the .slds-table--fixed-layout class, and there are a lot of columns available with some longer strings as values, the texts in the different columns in the white rows is displayed on top of each other. Note that this is not the case for the grey rows. Here the values are cut off when a new column starts.

**Comment by bekos** [comment]
@Nelsch Can you investigate if this is an issue with the Lightning CSS framework or it is something we do inside ng-lightning that causes this issue? Thx

**Comment by bekos** [comment]
The issue you see is because the white rows are actually, `<td>`'s with transparent background.
A workaround is to explicitly set background for this cells to white.

If you want, you can raise this issue to the repo of the LDS framework.
