### ISSUE TITLE
datepicker  formate

### ISSUE THREAD

**Issue by Jarvens** [ng-lightning/ng-lightning#303]
Hi 
    in my project have some where in use datepicker component . 
    but  i only found base example . that i want know is there have formate yyyy-MM-dd HH:mm:ss  ?

thanks!

**Comment by bekos** [comment]
Unfortunately we don't support custom formatter based on string. Your code  should be responsible to transform the output of the datepicker to the format you want.

I am closing this as I don't think we will add a date format option any time soon. Feel free to reopen if you need any more help on this. Thx
