### ISSUE TITLE
ng-icon not showing icon properly

### ISSUE THREAD

**Issue by nni123** [ng-lightning/ng-lightning#304]
If you are take a look at the component documentation at following URL ng-lightning.github.io/ng-lightning/#/components. Scroll down to to ng-icon and click on the "Try in plunker" button. If you look that the ng-icon in plunker it doesn't show ng-icon properly (no image just background color). You can view error message if you open link in chrome & open developer tool (Console should display). Main problem is assets/icons are not included in ng-lightning angularjs2 module.

NgLighing module config.js file has svgPath set to local "assets/icons" folder. I can't locate assets/icon anywhere or am I missing something obvious.

Thank you

**Comment by nni123** [comment]
moving to different library.

**Comment by bekos** [comment]
No problem really :) but you could probably search before opening another issue: https://github.com/ng-lightning/ng-lightning/issues/301#issuecomment-277355395
