### ISSUE TITLE
Compiling in Dev

### ISSUE THREAD

**Issue by JakeSchoermer** [ng-lightning/ng-lightning#305]
Hello ng-lightning folks,

My colleague and I are using ng-lightning for the first time in a project and we think we have found a bug and developed a small patch. We have tested this patch as a quick manual fix in the compiled npm package and have forked the repo in order to point our app at that, develop a PR that meets the standards documented and hopefully have it merged into this project.

I am however, having trouble compiling the project locally. I can run the tests with only a couple of errors, but cannot build the project.

When running ```npm run build``` I get the following error locally

```
[15:43:13] Finished 'clean' after 48 ms
[15:43:13] Starting 'ngc'...
[15:43:13] Starting 'lint:ts'...
no-unused-variable is deprecated. Use the tsc compiler options --noUnusedParameters and --noUnusedLocals instead.
[15:43:18] Finished 'lint:ts' after 5.01 s
[15:43:18] Starting 'ngc:templates'...
[15:43:19] Finished 'ngc:templates' after 686 ms
[15:43:19] Starting '__ngc'...
{ Error: Command failed: ./node_modules/.bin/ngc -p ./tsconfig.json
Error at /Users/jake/Source/MojoSoup/ng-lightning/node_modules/@types/jasmine/index.d.ts:39:52: '=' expected.
```

Obviously I have run ```npm install to get all of the dependencies``` so the problem really seems to be limited to TypeScript compilation.

I'm pretty new to TypeScript, so any assistance you can give would be greatly appreciated.

**Comment by mbryk** [comment]
There is a documented bug in the @types/jasmine package. 

`rm -rf node_modules/@types/jasmine`, change the dependency in package.json to `"@types/jasmine": "2.5.41"` and run `npm install` again.

http://stackoverflow.com/questions/42181156/error-in-at-loader-node-modules-types-jasmine

**Comment by bekos** [comment]
Hi @JakeSchoermer. Everything should work properly now on current master.
@mbryk Thanks for your help 👍 

Closing, but feel free to reopen if you still face any problem.
