### ISSUE TITLE
Lookup dropdown width parameter

### ISSUE THREAD

**Issue by sebitsi** [ng-lightning/ng-lightning#311]
Hi, 
is it possible to set dropdown (suggestion's window) with ?

Thanks for  advance.

Edvin

**Comment by bekos** [comment]
hi @sebitsi. It would be better to ask this kind of question on StackOverflow, but you could achieve what you want with CSS styles. Take a look at this example: https://plnkr.co/edit/EF6VOqwOmcOElZy3eSYN?p=preview

**Comment by sebitsi** [comment]
Hi, thanks.
I tried this too. Smaller is ok, but grater is not working.

**Comment by bekos** [comment]
Check again: https://plnkr.co/edit/EF6VOqwOmcOElZy3eSYN?p=preview
