### ISSUE TITLE
Relax peer dependencies to 4.0.0

### ISSUE THREAD

**Issue by Ketec** [ng-lightning/ng-lightning#312]
Unless there are plans to upgrade, could dependencies to be relaxed, @^2.0.0  caret does not seem to do the trick, so perhaps adding || >=4.0.0 might help?

**Comment by bekos** [comment]
@Ketec Thx for using ng-lightning. I changed `^2.0.0` to `>=2.0.0` in f2249356541286ea088205ae7cc8181f5b133bd0, which I believe should do the trick :)

It will be part of next release. Feel free to reopen if this is still an issue.
