### ISSUE TITLE
Workaround: Assets from lightning-design in Angular CLI (SVG, Images, etc)

### ISSUE THREAD

**Issue by mattisdada** [ng-lightning/ng-lightning#320]
This is a workaround for the poor souls who find this, it could be added into the readme if the devs like.

If you are using Angular CLI (1.0.0) and trying to get the assets working (SVG, Images, etc) you will need to move the assets from `node_modules/@salesforce-ux/design-system/assets` into `src/assets`.

This will expose the assets to the ng2 app to be loaded after compilation

You cannot modify the webpack config in Angular CLI (they will later open up a system for "addons")

**Comment by mgmarlow** [comment]
How are you bringing the SVG icons into the project with cli?

**Comment by mgmarlow** [comment]
Additionally, might be good to note that for those who are bringing in the SVG icons you need to add the additional declaration in the module import:

```
NglModule.forRoot({
  svgPath: '/assets'
})
```

**Comment by bekos** [comment]
Both are documented in the getting started section of our new demo page.
