### ISSUE TITLE
Input Select ngModel and ngFor options value

### ISSUE THREAD

**Issue by apat183** [ng-lightning/ng-lightning#322]
I don't know what I'm doing wrong but I can't seem to use the select with options. 

Using ```[(ngModel)]``` on the select just clears the item and using ngFor or ngValue on the options doesn't work.

```
<ngl-form-element label="Select Label" [error]="hasError ? error : null" class="slds-m-top--small">
  <select nglFormControl class="slds-select" [required]="required">
    <option>Option One</option>
    <option>Option Two</option>
    <option>Option Three</option>
  </select>
</ngl-form-element>
```

Any help would be great

**Comment by bekos** [comment]
@apat183 Thx for using ng-lightning, but this is not a problem of this library. You could find better help and support posting your question on StackOverflow. 

That said, you probably could use `[ngValue]` in each option. Check this plunker: http://plnkr.co/edit/v3CsDeWmISrL2LvEvbTD?p=preview
