### ISSUE TITLE
Feature Request: "ItemChange" Picklist Event

### ISSUE THREAD

**Issue by mgmarlow** [ng-lightning/ng-lightning#323]
Open up an (itemChange) event handler for the picklist. I'd like to be able to provide events directly to an `(itemChange)` handler on the picklist to handle changes in a custom way, rather than through `ngModel` updates.

Currently, implementing such behavior requires a little extra overhead of watching for the `open` attribute:

```typescript
class MyComponent {
  open: boolean = false;
  pick: string = 'No';
  picklistItems: string[] = ['Yes', 'No', 'Any'];
  constructor(private myService: myService) { }

  get pickLabel () {
    return this.pick || 'Select an option...';
  }

  onOpen () {
    if (!this.open)
      this.myService.updateData(this.pick);
  }
}
```

```html
<ngl-picklist [data]="picklistItems" [(nglPick)]="pick" [(open)]="open" (openChange)="onOpen()">
  <span class="slds-truncate">{{pickLabel}}</span>
  <template nglPicklistItem let-item>{{item}}</template>
</ngl-picklist>
```

You can see in this example that I have to watch for the `open` attribute, rather than handling the a change event directly.

I'd rather provide an event directly:

```typescript
onChange (item) {
  this.myService.updateData(item);
}
```

```html
<ngl-picklist [data]="picklistItems" [(nglPick)]="pick" [(open)]="open" (itemChange)="onChange()">
  <span class="slds-truncate">{{pickLabel}}</span>
  <template nglPicklistItem let-item>{{item}}</template>
</ngl-picklist>
```

**Comment by Bielik20** [comment]
I have encountered a similar problem and actually got [response on stackoverflow](https://stackoverflow.com/questions/44620270/how-to-listen-for-a-lookup-change), it also applies to Picklist component. I think it still would be beneficial to update documentation and then close the issue.

**Comment by bekos** [comment]
@mgmarlow `(nglPickChange)` is what you are looking for?

**Comment by mgmarlow** [comment]
Yeah that looks good to me. Didn't see the earlier comment since this thread has been out here for so long.

**Comment by napstercake** [comment]
If you pre-populate the _list items_ with _picks items_ the 'pickLabel' method seems to be perfect but if you selects 'No' on the dropdown again it's suppose to show an empty array of 'pick' but nope, you have 2 items there, did you realize?
