### ISSUE TITLE
Angular 4 and breadcrumb <template>

### ISSUE THREAD

**Issue by Ketec** [ng-lightning/ng-lightning#326]
Are there any plans to update for Angular4, currently it gives deprecation warnings.

https://github.com/ng-lightning/ng-lightning/blob/master/src/breadcrumbs/breadcrumbs.pug

**Comment by DaSchTour** [comment]
Take a look at #316

**Comment by bekos** [comment]
@DaSchTour Thanks 👍 

@Ketec It's planned.
