### ISSUE TITLE
angular 4 support

### ISSUE THREAD

**Issue by consigliory** [ng-lightning/ng-lightning#328]
looks like current npm package does not support angular 4. ng-lightning@1.3.0 wants @angular/core@>=2.0.0

**Comment by bekos** [comment]
do you get a warning when installing ng-lightning with Angular 4?

**Comment by nadworny** [comment]
For me it also doesn't seem to work with Angular 4 (I'm using JHipster 4.6.0). It gets installed without an issue, but then displaying of the components somehow doesn't work (here spinner and breadcrumbs):
![image](https://user-images.githubusercontent.com/1425919/27949574-76920f20-62fe-11e7-958b-6fa9088e0553.png)

**Comment by nadworny** [comment]
thanks a lot guys for fixing it! Do you know already when is the next release coming with these changes?

**Comment by esarbanis** [comment]
@nadworny ng-lightning 2.0.0 just got released ;)

**Comment by bekos** [comment]
Actually is 2.0.1 because of an issue we had with NPM publishing! Enjoy :)

**Comment by nadworny** [comment]
Thanks a lot guys! Tried it out and still have some issues...
I've created a sample jhipster project and added ng-lightning to it... would you care checking it out or should I just create an issue on github? https://github.com/nadworny/jhipsterNgLightning
You can start the backend by executing "mvn" command and ui by "yarn install & start"
Upon start this page will be opened: src/main/webapp/app/home/home.component.html
I've added there some examples from ng-lightning

**Comment by esarbanis** [comment]
I couldn't spot the module you actually imported ngl and so once I added `NglModule.forRoot()` in `src/main/webapp/app/home/home.module.ts` `imports` I was able to see the ngl components.

**Comment by nadworny** [comment]
Hmm that's interesting 👍 
It was imported in the ```src/main/webapp/app/app.module.ts``` so the main module of the application... I'll try later today what you suggested! Thanks!

**Comment by nadworny** [comment]
Yeah, it works! Thanks a lot!
