### ISSUE TITLE
Lookup value delete

### ISSUE THREAD

**Issue by egabe** [ng-lightning/ng-lightning#330]
How can I delete the value of the lookup from code after a search? Now I have to click the x in the input field. I tried set null value, but it didn't work.

**Comment by xGeiben** [comment]
Hello egabe, this worked for me:
first: set [pick]="null"

`<ngl-lookup  [(value)]="value" [lookup]="lookup" [searchIcon]="false" [pick]="null" (pickChange)="changed($event)" field="tags">`


second:
in your changed method after you did whatever you need with the value selected just set 
this.value = "";
`changed(event: any):void
{
   // Your code
    this.value = "";    
  }` 
and it will be cleared, I hope this works for you!

**Comment by esarbanis** [comment]
Hope @xGeiben answer covers you :slightly_smiling_face:
