### ISSUE TITLE
Add support for ng-template since template is depreciated

### ISSUE THREAD

**Issue by Fufuxx** [ng-lightning/ng-lightning#331]
In Angular 4, template is Deprecated (replaced by ng-template).

<img width="1435" alt="screen shot 2017-04-25 at 9 08 57 am" src="https://cloud.githubusercontent.com/assets/3042466/25374917/02f9f5be-2997-11e7-9475-2944fa25f1a1.png">

**Comment by mattisdada** [comment]
Looks like someone submitted a PR to get this fixed but the tests failed:
https://github.com/ng-lightning/ng-lightning/pull/333

**Comment by kgalanop** [comment]
@mattisdada, not sure why the tests failed. I have updated the PR with another feature and it seems that tests pass now
