### ISSUE TITLE
Popover wrong placement with dynamic template content

### ISSUE THREAD

**Issue by vvaldersteins** [ng-lightning/ng-lightning#334]
Hi,

In case popover template has a dynamic content, it's out of placement.

For example -

```
<template #text>
   <div *ngFor="let text of texts">
       {{text}}
   </div>
</template>
```

Would show the popover in wrong place, which would be fixed after scrollign down or up.

Just wondering if there is any fix for this?

**Comment by vlichtenberg** [comment]
I can only reproduce this with "top" positioned popovers containing variable text. I wouldn't know how to fix it other than to just use another direction.

**Comment by jercoh** [comment]
I am able to reproduce this issue with any popover template containing a list of elements generated by `*ngFor`.
This bug occurs with `left` or `right` positioned popovers.

**Comment by bekos** [comment]
With the new 4.0 version we rely on Angular's CDK for popover/tooltip placement instead of Tether, and it seems that this issue is now handled correctly.
