### ISSUE TITLE
When using ng-lookup in a form the spacing is not correct. 

### ISSUE THREAD

**Issue by jjulicher** [ng-lightning/ng-lightning#337]
Even though the internal divs have the slds-form-element it requires the ngl-lookup to have the attribute class="slds-form-element" or be wrapped in a div with the .slds-form-element class to get the correct spacing... 

is there any way that you can change the output so that the ngl-lookup markup is changed to a div - I think  in angular 1.x there was a way to do this not sure about angular 2+. 

thanks

**Comment by bekos** [comment]
There has been a new release v4.0. Check if your issue is still valid and please use the Stackblitz button to reproduce it and helps us track it.
