### ISSUE TITLE
Multiple NglDropdown intermittent undefined error

### ISSUE THREAD

**Issue by ronnyek** [ng-lightning/ng-lightning#338]
Every now and then navigating away from a view that has multiple ngl dropdowns on it blows up with an error saying:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'unsubscribe' of undefined
TypeError: Cannot read property 'unsubscribe' of undefined
    at NglDropdown.ngOnDestroy (dropdown.js:55)
```
That line is in the ngOnDestroy attempting to unsubscribe from the openEventEmitter. I see lots of things that could contribute... the fact that the openEventEmitter is defined as a const outside the component itself (may be intentional design)

Maybe there should just be a simple check to see if subscription exists yet?

https://github.com/ng-lightning/ng-lightning/blob/69c72b89aa0f33c10aba24bab8452bf268fe0bad/src/menus/dropdown.ts

**Comment by Chyngyz** [comment]
Having same error, in my case it appears when I pass data to ReplaySubject.

**Comment by Chyngyz** [comment]
I resolved my issue by investigating my use of ReplaySubject, it appears I didn't clear the subscriptions on component destroy.

**Comment by Stwissel** [comment]
@Chyngyz can u post a working sample with the parts highlighted you had to change

**Comment by bekos** [comment]
I believe this will be fixed via https://github.com/ng-lightning/ng-lightning/commit/330e66b92ad701e476eef274f31ecfd8f6e5b710. It will be part of the next release (not very far away). Feel free to reopen if this still occurs in the next version.
