### ISSUE TITLE
Icons disappear after transition to other page and coming back 

### ISSUE THREAD

**Issue by kuiperr005** [ng-lightning/ng-lightning#340]
**Angular version**: 4.1.3
**Ng-lightning**: 1.3.0
**What I did:** 
I have copied the icon assets to my public assets folder, like you explain in the README, following your webpack config. I have added the following markup in my template:
`<ngl-icon icon="search" type="default" svgClass="slds-input__icon slds-input__icon_left"></ngl-icon>`

Somehow at first load, the icon is visible, but after leaving the page and coming back, the 
`<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="assets/icons/utility-sprite/svg/symbols.svg#search" x="0"></use>` 
has a size of 0 x 0 and the icon doesn't show up.

**Comment by kuiperr005** [comment]
Looks like this is a bug in Chrome:
https://stackoverflow.com/questions/35049842/svgs-in-chrome-sometimes-dont-render

**Comment by rotvulpix** [comment]
As said in the stackoverflow question this was fixed in Chrome 50, current version is 60. This issue should still be open?

**Comment by kuiperr005** [comment]
I am already using the higher version of Chrome but this issue still exists. Maybe there is a workaround, but I haven't found one yet. If I disable cache in the developer console, this issue does not exist, so can we force-disable caching of the svg sprite assets in some way?

**Comment by bekos** [comment]
@kuiperr005 Is there something I can see it happen? On our demo page this doesn't seem to be a problem.
