### ISSUE TITLE
Lookup: add 'required' attribute to input element

### ISSUE THREAD

**Issue by kuiperr005** [ng-lightning/ng-lightning#343]
Hi, Is it possible to add a 'required' attribute to the input element of the lookup? Would be very useful in my forms.

**Comment by esarbanis** [comment]
Hi @kuiperr005, the main use case of a lookup is in a search filter, in which you should allow an empty value (unfiltered search). Can you explain your use case a bit more?

**Comment by kuiperr005** [comment]
Hi @esarbanis, thanks for your reply, I am using the lookup to filter a large list of properties and select a single property for creating a new resource in a CRUD app. I use this component in the create form, because I have a lot of items, otherwise I would have used the picklist instead.

Main reason is validation of the form. I want to disable the submit when the lookup has no value.

**Comment by esarbanis** [comment]
@kuiperr005 a way around it of course would be to check the `value` of the `pick` event on form submission.

We are evaluating the possibility to alter the lookup's component API, by exposing the `input` element (much like we do in form elements), but it wouldn't be a small change. If you are up to it a PR would be welcome ;)

**Comment by kuiperr005** [comment]
hi @esarbanis, for now I'll go with the workaround, but I may look into it in the future, Thanks anyway!

**Comment by esarbanis** [comment]
In that case I am going to go ahead and close this. Feel free to reopen it if you feel like looking into it at a later point in time.
