### ISSUE TITLE
Clipped text in polymorphic lookup widget in IE 11

### ISSUE THREAD

**Issue by DanielLangdon** [ng-lightning/ng-lightning#347]
I can't say for sure why the behavior of the polymorphic lookup is different in IE11 versus other browsers, but there is a major problem that the search key typed by the user is not only clipped, but sometimes bounces up and down as focus and cursor move in and out of the text box.  Also, the polymorphic lookup widget appears smaller than other similar widgets.

This behavior even appears in the example shown at "https://ng-lightning.github.io/ng-lightning/#/components" (Scroll down to the "Lookups" section and find the "Polymorphic" subheading.

I studied this carefully because I have a requirement to make this widget work with IE11.

The solution that works for me is to manually set the height of the text box to 32px.  This seems to solve the problem perfectly in IE11 without causing issues in other browsers.  I would like to suggest that the CSS be modified to apply the style to the input box so that developers supporting IE11 don't have to do it manually. (As a plus, it will fix the style on your example page!)
![ie11 trouble 1](https://user-images.githubusercontent.com/4664719/30455275-89ef32ac-995c-11e7-94d1-19415975c07a.png)
![ie11 trouble 2](https://user-images.githubusercontent.com/4664719/30455277-8be12412-995c-11e7-9988-a194b695413b.png)

**Comment by bekos** [comment]
I don't think it's relevant any more. There have been many new releases of LDS that seem to solve this issue.
