### ISSUE TITLE
nglPopoverDelay="[1000, 2000]" behaves like nglPopoverDelay="0"

### ISSUE THREAD

**Issue by wgerven** [ng-lightning/ng-lightning#351]
In the docs it is stated

    nglPopoverDelay?: number | number[]: Delay in milliseconds until it opens/closes. 
    
`If you wish to specify different delays for opening and closing, you may provide an array of two different values.`

If I provide this array, say `[1000, 2000]`, then the net effect is that there is no delay at all. This behaviour is also reproduced in the relevant plunker. Simply providing a number does behaves as expected.

Do I miss anything?

P.s. I'm at `salesforce-ux/design-system` 2.4.3 and `ng-lightning` 2.0.1.

**Comment by bekos** [comment]
Can u please provide the plunker?

**Comment by wgerven** [comment]
Hi, it's your own plunker for popovers (I cannot link to it, there's only a generic URL). If I change there `nglPopoverDelay` to above delay, it shows the behavior; this one:

change 

    <a nglPopover="I open and close with 1 second delay..." nglPopoverBehavior nglTooltip nglPopoverDelay="1000" #x="nglPopover">Hover me!</a>

to

    <a nglPopover="I open and close with 1 second delay..." nglPopoverBehavior nglTooltip nglPopoverDelay="[1000, 2000]" #x="nglPopover">Hover me!</a>

**Comment by bekos** [comment]
This should be a variable, ie `[nglPopoverDelay]="[1000, 2000]"`. Does this work?

**Comment by wgerven** [comment]
Yes! Thanks, this solved it! Is this expected behavior? (I.e., I could/should have known this?)

**Comment by bekos** [comment]
Yes, it is standard angular behavior :) If not in brackets it is just a string.

**Comment by wgerven** [comment]
Thanks, sorry then for bringing this up, didn't realize that!
