### ISSUE TITLE
[ URGENT ] Support for Angular 5.0

### ISSUE THREAD

**Issue by xGeiben** [ng-lightning/ng-lightning#353]
Hello guys today i updated my project to the new release of Angular (5.0) and i encounter a problem in one of the files of ng-lighting, config.d.ts to be more precise, because we were using OpaqueTokens from the @angular/core module, but that library got deprecated.
import { EventEmitter, OpaqueTokens } from '@angular/core';     <- Now needs to be 
import { EventEmitter, InjectionToken } from '@angular/core';      <- Like this

Please someone fix this because my project won't work correctly because of this.
thanks in advance.

**Comment by bekos** [comment]
@xGeiben which version are you using?

**Comment by xGeiben** [comment]
currently 1.3.0, ill update it to see if that fix it :)

**Comment by xGeiben** [comment]
It did fix the problem, my bad, i should've check the version before posting this but i panicked, Thanks for the hint. 
But now i'm encountering some  errors related to the templates, i think that its because the template tag got deprecated.

ERROR Error: Uncaught (in promise): Error: Template parse errors:
"let-" is only supported on ng-template elements. ("nglLookupHeader class="slds-text-body--small">Technologies</div>
          <template nglLookupItem [ERROR ->]let-brand>
              <div class="row align-items-center">
                <div class="col-md-1""): ng:///QuestionModule/QuestionFormComponent.html@58:34
Error: Template parse errors:
"let-" is only supported on ng-template elements. ("nglLookupHeader class="slds-text-body--small">Technologies</div>
          <template nglLookupItem [ERROR ->]let-brand>
              <div class="row align-items-center">
                <div class="col-md-1""): ng:///QuestionModule/QuestionFormComponent.html@58:34

**Comment by bekos** [comment]
Seems like this code, is on your own side, not in the library.

**Comment by xGeiben** [comment]
thats true, my bad :)
