### ISSUE TITLE
modal openChange issue

### ISSUE THREAD

**Issue by lucabenedettini** [ng-lightning/ng-lightning#354]
Hi,
I'm trying to chatch openChange event in ngl-modal component (i.e. click on close icon event). I did this:

<ngl-modal header="Smart Engine Wizard" [(open)]="opened" [size]="size" (openChange)="closeIcon($event)">..... in html component
 
closeIcon(stage:boolean){
    console.log('closeicon clicked');
  } in ts

but it throw the error co.closeicon is not a function.

**Comment by esarbanis** [comment]
A simple test case or a plunker would shed some more light to this issue :)

**Comment by esarbanis** [comment]
Feel free to re-open if you still experience this issue.
