### ISSUE TITLE
Export separate module per component

### ISSUE THREAD

**Issue by esarbanis** [ng-lightning/ng-lightning#358]
It would be nice to give the ability to the user to load only the components (s)he is using.

**Comment by ihym** [comment]
This should work even now.
eg: import {NglTabsModule} from 'ng-lightning/tabs/module';

You can also configure it (if it is configurable) by injecting NglConfig to the app module.

**Comment by esarbanis** [comment]
Thank you @ihym for your feedback, maybe we can put this information in our documentation :wink:
