### ISSUE TITLE
Upgrade to slds 2.5.0

### ISSUE THREAD

**Issue by fervanrijswijk** [ng-lightning/ng-lightning#363]
Hi,

For a project I am upgrading SLDS to version 2.5.0 until I saw ng-lighting is tested for 2.2.1.
Are there any plans to update to this/newest SLDS version?

**Comment by esarbanis** [comment]
Hi @fervanrijswijk,

We are in the process of migrating our components to SLDS v2.5.0, so stay tuned.

Also please make sure to reach out to our [gitter](https://gitter.im/ng-lightning/ng-lightning) for these kind of questions :slightly_smiling_face:

**Comment by fervanrijswijk** [comment]
Thanks for the quick response and positive! And thanks for pointing me to gitter as well :-)
