### ISSUE TITLE
Lookup does not have autocomplete=off attribute

### ISSUE THREAD

**Issue by Matiszak** [ng-lightning/ng-lightning#369]
ng-lookup component does not render `autocomplete="off"` attribute in html regardless of the fact that `autocomplete="off"` is present in .pug file : [lookup.pug](https://github.com/ng-lightning/ng-lightning/tree/master/src/lookups/lookup.pug). 

In pug file:
`... input.slds-input.slds-lookup__search-input(#lookupInput, [id]="inputId", type="text", aria-autocomplete="list", role="combobox", autocomplete="off", ...`

In lookup.js in node_modules/ng-lightning/lookups/lookup.js
`... <input class=\"slds-input slds-lookup__search-input\" #lookupInput [id]=\"inputId\" type=\"text\" aria-autocomplete=\"list\" role=\"combobox\" [attr.aria-expanded]=\"!!expanded\" [attr.aria-activedescendant]=\"optionId(activeIndex)\" [ngModel]=\"inputValue\" (ngModelChange)=\"onInputChange($event)\" (keydown.Esc)=\"close($event)\" [placeholder]=\"placeholder || ''\" (keydown.ArrowDown)=\"moveActive($event, 1)\" (keydown.ArrowUp)=\"moveActive($event, -1)\" (keydown.Enter)=\"pickActive($event)\" [ngClass]=\"{'slds-input': !polymorphic, 'slds-input--bare': polymorphic}\"> ...`

**Comment by esarbanis** [comment]
HI @Matiszak , the fix with the `autocomplete="off"` will be included in the next version of ng-lightning, comming up very soon.

We wan't to squeeze-in a couple of bugs more into that version, so stay tuned for the next release.

I am closing this, but if you see that this happens after the next release, feel free to re-open it.
