### ISSUE TITLE
ngOnDestory() method on datatable.ts unable to handle null variable.

### ISSUE THREAD

**Issue by arsalankhatri** [ng-lightning/ng-lightning#373]
Kindly put if condition on ngOnDestroy method of datatable.ts

  ngOnDestroy() {
    this._columnsSubscription.unsubscribe();
    }
==>
  ngOnDestroy() {
    if(this._columnsSubscription){
    this._columnsSubscription.unsubscribe();
    }
}

**Comment by bekos** [comment]
Fixed via 4f4c013ffe6dc3dc5b29cf7be011de1cce9c9d4d. Thx.
