### ISSUE TITLE
Picklist with keyboard navigation support

### ISSUE THREAD

**Issue by abelardolg** [ng-lightning/ng-lightning#375]
I have tried in plunker your picklist component. When I have tried the keyboard to select any option I couldn't move between options with the down arrow. 
I would appreciate to add keyboard supporting to this component in order to navigate among its options and confirm with the enter.

Best regards.

**Comment by bekos** [comment]
Sorry but I see keyboard navigation in picklist towork both in our demo page and in plunker. Also there are tests to confirm this behavior. I am going to close it for now but feel free to reopen if you have more information about it.

**Comment by abelardolg** [comment]
Yes, @bekos : you are right, obviously your component can be traversed by keyboard navigation.

I am trying to dress your component with bootstrap v4 now. 

Best regards.
