### ISSUE TITLE
ngl-datatable data is not updated when changed

### ISSUE THREAD

**Issue by Niondir** [ng-lightning/ng-lightning#376]
Version 2.0.1

Template:
```
<table ngl-datatable [data]="data" trackByKey="name" class="slds-max-medium-table--stacked-horizontal">
  <ngl-datatable-column heading="Channel" key="name" cellClass="slds-truncate" sortable>
    <ng-template nglDatatableCell let-value><b>{{value}}</b></ng-template>
  </ngl-datatable-column>
</table>
```

Component:
```
export class ChannelsComponent{

  data: Channel[];

  constructor(private channels: DataService) {
    channels.channels.subscribe((chans) => {
      console.log("update chans!");
      this.data = [];
      setTimeout(()=> this.data = chans, 0);
    });
  }
}
```

Without setting the data to an empty array first and the setTimeout "hack" the data does not update.

**Expected behavior:**
It should work to just update the data by setting `this.data = chans`

**Comment by bekos** [comment]
Can you please provide the plunker link? Normally you have to change reference to the data object, since for performance reasons this has `OnPush` strategy.

**Comment by Niondir** [comment]
I guess it was related to some local caching and not changing the reference. After getting data from server it's fixed.
