### ISSUE TITLE
Picklist: Duplicated values using objects.

### ISSUE THREAD

**Issue by napstercake** [ng-lightning/ng-lightning#387]
Hi all, I'm prepopulating the picklist with an object like the picklist [example](http://ng-lightning.github.io/ng-lightning/#/components) but when I deselect a value already selected by the initial loading, the pick items adds a new object instead of delete it from the array. Here's an example of what is doing right now: https://codesandbox.io/s/5095zr5x44 any help?

**Comment by bekos** [comment]
There has been a new release v4.0. Check if your issue is still valid and please use the Stackblitz button to reproduce it and helps us track it.
