### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by aniruddhadas9** [ng-lightning/ng-lightning#390]
I am trying to use this in my new angular 7 project and it loos like this does not support angular 6 onwards. Is there any plan to upgrade to use this with angular 7 or atleast 6 above with rxJs 6 

Below is the error if try to use with angular 7
```
  ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/pick/pick.js
  Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in '/spmepath/node_modules/ng-lightning/pick'
    ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/Observable' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/add/observable/of' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/add/operator/debounceTime' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/add/operator/distinctUntilChanged' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/add/operator/do' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/picklist/picklist.js
  Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in '/spmepath/node_modules/ng-lightning/picklist'
    ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/add/operator/publish' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/add/operator/skip' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/lookups/lookup.js
  Module not found: Error: Can't resolve 'rxjs/add/operator/switchMap' in '/spmepath/node_modules/ng-lightning/lookups'
    ERROR in ./node_modules/ng-lightning/popovers/trigger.js
  Module not found: Error: Can't resolve 'rxjs/add/operator/take' in '/spmepath/node_modules/ng-lightning/popovers'

**Comment by AnBauer** [comment]
I upgraded the entire lib but unfortunately got no answer to my question wether they would be willing to integrate that major refactoring in the master. 
As the project I‘m working for is also heading from ng6 to 7 I will publish that version under ngx-lighting within the next days. My firm is going to continue support this lib...
I‘ll post here when it is available.

**Comment by sroettering** [comment]
This lib looks amazing and I would love to use it. If only it would be better maintained. Looking forward to your fork @AnBauer

**Comment by rodrigoEclipsa** [comment]
@AnBauer we have to use cdk of angular material to improve components

**Comment by AnBauer** [comment]
I know, I'm late but finally I managed to publish my version of ng-lightning. Unfortunately, my request in the gitter chat from October '18 is still unanswered, so I decided to move forward with a new package name. It is called `ngx-lightning` and will receive constant updates and fixes. If there are important fixes in ng-lightning, I'm going to port them to ngx-lightning as well.

**Comment by AlaMote** [comment]
@AnBauer trying to start new project with you package (`ngx-lightning`), but have this problem:

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ngx-lightning/ngx-lightning' in 'PATH/src/app'

In app.module.ts I have this:

`
import { NglModule } from 'ngx-lightning/ngx-lightning';

@NgModule({
  declarations: [
     ...
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    RouterModule,
    NglModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
`
For what reason can this error appear? Thanks

**Comment by AnBauer** [comment]
Actually, that would be an issue / a question within the ngx-lightning project, not here. But a quick hint: the import should be `import { NglModule } from 'ngx-lightning';`

**Comment by AlaMote** [comment]
@AnBauer got it, thank you anyway

**Comment by bekos** [comment]
There is a new release v4.0.0 🎉 with support for latest Angular and LDS. Check my comment: https://github.com/ng-lightning/ng-lightning/issues/378#issuecomment-476013557
