### ISSUE TITLE
Can't build --prod with dependency to "tether": "1.4.5"

### ISSUE THREAD

**Issue by dmnBrest** [ng-lightning/ng-lightning#391]
Build --prod fails with this strange error

ERROR in main.697c6bb9fbe91f7b6b2a.js from UglifyJs
undefined

I found difference in two projects I have and there is a reference to "tether": "1.4.5" that fails build --prod
Here is some mentions regarding this issue
https://github.com/HubSpot/tether/issues/291
https://github.com/angular/angular-cli/issues/12414

Is it possible to fix it. I can't build my project.

**Comment by bekos** [comment]
@dmnBrest Thanks for bringing this into my attention. Can you please try the latest version (3.0.0) and let me know if there is still a problem.
