### ISSUE TITLE
PickList: check mark does not appear when value set in code

### ISSUE THREAD

**Issue by AlaMote** [ng-lightning/ng-lightning#411]
When I set default value of PickList, it does not show check mark as if I would manually select a value. Is there a way to solve this problem?

component.html
```
<ngl-picklist nglFormControl
        filter="label"
        [data]="data"
        [(nglPick)]="selected"
        [(open)]="open"
        [nglPickMultiple]="multiple">
    <span class="slds-truncate">{{getPickLabel()}}</span>
    <ng-template nglPicklistItem let-item>{{item.label}}</ng-template>
</ngl-picklist>
```

component.ts
```
selected = {label: 'Tier 1', value: 1};
data = [
    {label: 'All tiers', value: null},
    {label: 'Tier 1', value: 1},
    {label: 'Tier 2', value: 2},
    {label: 'Tier 3', value: 3}
]
```

![image_2019_02_22t14_04_34_296z](https://user-images.githubusercontent.com/9486443/53248273-03fb5580-36be-11e9-9b2e-9b9513cc0eac.png)

**Comment by bekos** [comment]
There has been a new release v4.0. Check if your issue is still valid and please use the Stackblitz button to reproduce it and helps us track it.
