### ISSUE TITLE
Icons do not work in new project and on example stackblitz

### ISSUE THREAD

**Issue by paustint** [ng-lightning/ng-lightning#444]
It seems that the icons do not work. I just started a new project to test things out and I was unable to get icons to show up. When I looked on the examples on StackBlitz, the icons did not work there either.

I was able to get the icons to work by manually copying the icon folder into my asset folder (I struggled trying to get it to work using a glob for the angular build process - but should be possible).  

I think the getting started guild should include some guidance on what is required to ensure icons work.

https://ng-lightning.github.io/ng-lightning/#/components/icons

![image](https://user-images.githubusercontent.com/5461649/55689777-fcc69900-5945-11e9-8a32-17f56af974fc.png)

![image](https://user-images.githubusercontent.com/5461649/55689783-0b14b500-5946-11e9-8855-e0ce3b9e5fbc.png)

**Comment by bekos** [comment]
@paustint Thx for pointing out this issue to us :) Actually, our demo page is an Angular CLI project and we use the same steps to make it work as on any other new angular-cli project. I describe the new step here: 9bff21bc890e77bb5298eecf26522708d78714e6.

In brief you have to add this snippet to your `assets`:
```
{
    "glob": "**/*",
    "input": "node_modules/@salesforce-ux/design-system/assets/",
    "output": "/assets"
  },
```
