### ISSUE TITLE
AOT Production Build Error

### ISSUE THREAD

**Issue by SIlver--** [ng-lightning/ng-lightning#448]
### Type of Issue
[x] Bug Report
[ ] Feature Request
### Description
I'm using your package to build my library to be compiled to js. I've compiled everything without any problems, but when I'll want to consume my library with ng build --prod (AOT enabled), I'm getting error:

> ERROR in Error during template compile of 'Module'
>   Function calls are not supported in decorators but 'NglModule' was called.

ng --prod --aot=false won't produce any errors.

**Comment by ihym** [comment]
Our demo uses AOT for production builds, and works fine.
This shouldn't be related to the library.
