### ISSUE TITLE
General accessibility issue (Info and Relationships) for comboboxes

### ISSUE THREAD

**Issue by thowoo** [ng-lightning/ng-lightning#462]
Drop down menus (select boxes or role="listbox") should always have a description that is explicitly associated with the field to make sure that users of assistive technologies will also know what the field is for.

Attached please find the details for report generate for 'comboboxes'.
![comboboxes - accessibility issue](https://user-images.githubusercontent.com/31666497/56813963-199b1180-680c-11e9-883a-a7726a2c5e34.JPG)

**Comment by bekos** [comment]
Hi @thowoo :-) We are following the markup specs as they are defined from LDS https://www.lightningdesignsystem.com/components/combobox/ 
Is there something that we have missed? If not, I think it would be better to open the issue about accessibility to the LDS repo. WDYT?

**Comment by thowoo** [comment]
Hi, you are right. I will create the issue to LDS repo. Thanks!

**Comment by bekos** [comment]
@thowoo 👍 Keep us updated if we miss any change from LDS.
