### ISSUE TITLE
Issue - Dynamic options for RadioGroup

### ISSUE THREAD

**Issue by thowoo** [ng-lightning/ng-lightning#467]
OS: Windows 10
Browser: Chrome latest version
Angular version: 7
Ng-lighting version: 4.3
LDS: 2.8.3

When using dynamic options for Radio-Group, 'ExpressionChangedAfterItHasBeenCheckedError' is reported by console

Re-produce link:
https://stackblitz.com/edit/angular-fpunlt?file=src%2Fapp%2Fbasic.html
need to open console to see the error

![image](https://user-images.githubusercontent.com/31666497/57049736-5f5e3c80-6c47-11e9-8f47-e7d9f2d0cc64.png)

**Comment by bekos** [comment]
Hi again @thowoo and thanks for your issue reports 👍 

This is fixed via 2357b5af7c0899424443a6c07612f4c93aee1a1d and will be part of the next release, probably this weekend.
