### ISSUE TITLE
Scroller for Combobox has issue when put combobox inside <main>

### ISSUE THREAD

**Issue by thowoo** [ng-lightning/ng-lightning#472]
OS: Win10
Browser: Chrome V72.0
Angular: V7
Ng-lightning: 4.4.0

Issue:
Put combobox under `<main></main>,` the drop down list will disappear when click on the scroller. 
StackBlitz link: [https://stackblitz.com/edit/angular-upuhte?file=src%2Fapp%2Fapp.component.html](url)

**Comment by bekos** [comment]
Hi @thowoo :) Nice catch and nice reproduce scenario 👍 
I will prepare a fix for this.
