### ISSUE TITLE
Issue: drop down list of combobox is not 'stick' to Input when put combobox inside the modal

### ISSUE THREAD

**Issue by thowoo** [ng-lightning/ng-lightning#478]
OS: Win10
Browser: Chrome V72.0
Angular: V7
Ng-lightning: 4.5.1

click on the combobox then scroll down with mouse out of the frame of drop down list. The drop down list should stick with the combobox(input) but does not.

StackBlitz link: [https://stackblitz.com/edit/angular-upuhte?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-upuhte?file=src%2Fapp%2Fapp.component.html)

**Comment by bekos** [comment]
@thowoo Thx for the report 👍  I will send a fix soon :)
