### ISSUE TITLE
Datepicker : I18N on "Today" and "Select a date" tooltip

### ISSUE THREAD

**Issue by Worlor** [ng-lightning/ng-lightning#482]
Hello,

I'm using this component for a french WA.
The weekdays are well translated, but can you add the possibility to personalize the "Today" button and also the "Select a date" tooltip on input of the component.

Thank you

**Comment by bekos** [comment]
hi @Worlor. This will be fixed on the next release via d7d9bf8573bf1b471b71eda51155b839366c44ab.

**Comment by Cheftryade** [comment]
Hi, can you please add these properties to datepicker-input ? I can't use them with this component.

**Comment by bekos** [comment]
@Cheftryade Of course. Totally forgot about it!

**Comment by bekos** [comment]
Fixed via 2bcedc18477215b12b73b8592dccfc6c406e5b85.
