### ISSUE TITLE
Datepicker-input : validation error when date initialized by ControlForm

### ISSUE THREAD

**Issue by Worlor** [ng-lightning/ng-lightning#483]
Hello,

I'm using Ngl-Datepicker-input for a Date input.
I want to use it with a FormControl with a pre-filled date.

So here is the HTML :
```html
<ngl-datepicker-input format="little-endian" [formControl]="dateTarifControl" label="Date tarif" [class.slds-has-error]="dateTarifControl.invalid"></ngl-datepicker-input>
```

and the Typescript : 
```ts
const date = new Date(2019, 5, 21); // just for example
this.dateEffetControl = new FormControl(moment(date).format('DD/MM/YYYY'),[Validators.required]);
```

The component mark the input invalid with this error : 
![image](https://user-images.githubusercontent.com/3814031/59046313-14f16080-8882-11e9-80f3-57f04c00349b.png)

Is there a way to init the ngl-datepicker-input with a pre-filled date, using it with reactive form ?
Thanks

**Comment by bekos** [comment]
@Worlor The datepicker works with `Date` objects, not strings. So you have to do:
`this.dateEffetControl = new FormControl(new Date(2019, 5, 21), [Validators.required]);`

**Comment by Worlor** [comment]
Thanks for reply, I have tried this, but the problem was elsewhere.
The bug was coming from the object returned from my service (a date attribute that was, in fact, a string...)
