### ISSUE TITLE
Combobox disabled property

### ISSUE THREAD

**Issue by MartynenkoA** [ng-lightning/ng-lightning#498]
Does combobox have disabled property?
Does combobox have "not clearable" property?

**Comment by jesusbarcenilla** [comment]
This ticket is a bit old but You can use the standard disabled attribute in the input element.

`<input nglCombobox placeholder="Select an Option" disabled>`

I couldn't find anything for the "not clearable" option. I think i'm going to open a new issue for that.

**Comment by bekos** [comment]
What @jesusbarcenilla suggested is correct and the behavior of the combobox for selection has changed.
