### ISSUE TITLE
Reduce logging on tdd

### ISSUE THREAD

**Issue by ppolyzos** [ng-lightning/ng-lightning#5]
When running on `tdd` mode there is too much logging info from [watcher], displaying all the files that are changed to .js, which is normal as all files are transpiled from typescript to javascript.

I would suggest an option `--verbose` and by default the logging to display only errors and warnings.

**Comment by esarbanis** [comment]
Something like that?

**Comment by ppolyzos** [comment]
Yes! This reduces all the noise from generated javascript files.

**Comment by bekos** [comment]
Reopening as I would like to have this configurable from command line. cc @esarbanis
