### ISSUE TITLE
ngl-combobox opens on bottom of page

### ISSUE THREAD

**Issue by Niondir** [ng-lightning/ng-lightning#506]
When opening the ngl-combobox the popup is opend at the bottom of my page in a `cdk-overlay-container`.

Is there any way to fix this or do you need some example app for reproduction?

**Comment by bekos** [comment]
I cannot reproduce on our demo site. Plz provide a reproduction.

**Comment by Niondir** [comment]
I missed to include some required CSS file.

**Comment by adasgupta** [comment]
Hi @Niondir , I am facing the exact same issue with my combobox. Can you please let me know the css fix that worked for you? Thanks!
