### ISSUE TITLE
Update project to support Angular v9

### ISSUE THREAD

**Issue by jefersonla** [ng-lightning/ng-lightning#508]
It's possible update only the package.json of this library to support Angular v9?

**Comment by jesusbarcenilla** [comment]
I also had problems whit the peer dependencies in /projects/ng-lightning/package.json.

As a work around you can just use --force to update them. That worked for me.

**Comment by bekos** [comment]
@jefersonla v6.0.0 already supports Angular v9. what error exactly do you get?

**Comment by Svitra** [comment]
The request to update to Angular 9 is required only to avoid the warnings in npm - with version 6 i am still getting warnings about required peer dependencies for Angular 8.

**Comment by jefersonla** [comment]
Like @Svitra said, we are receiving some warnings in npm about required peer dependencies for Angular 9.
