### ISSUE TITLE
ngl-combobox should not toggle the selection when is used as a picklist

### ISSUE THREAD

**Issue by jesusbarcenilla** [ng-lightning/ng-lightning#509]
When the user click in picklist item that is already selected it should remain selected.

The current behaviour deselect the item. That is ok for a multi selection picklist but for the basic one i think is not what an user expects.

I've open a pull request with a possible solution #507

**Comment by bekos** [comment]
@jesusbarcenilla Although a bit late, thx for your contribution. You are right 👍
