### ISSUE TITLE
`ngl-checkbox-option` label not being displayed when iterated over RxJS Subject values

### ISSUE THREAD

**Issue by gagan-lokesh** [ng-lightning/ng-lightning#512]
I am displaying multiple `ngl-checkbox-option` components by iterating over RxJS `Subject` 
 values with the help of async pipe as shown below.

```
<fieldset ngl-checkbox-group label="Field label">
  <ngl-checkbox-option *ngFor="let entry of entries|async" [label]="entry">
    <input ngl type="checkbox" />
  </ngl-checkbox-option>
</fieldset>
```
where `entries` is of type `Subject<String[]>`.

The component is being rendered as below. There are no labels displayed and also the styling is broken.

![image](https://user-images.githubusercontent.com/40685619/81085218-8c0cfa00-8f14-11ea-9e17-477736f17ef1.png)

\
If I iterate over a normal JS array, I am able to see the labels for all the options and they're styled correctly.

---

**Angular**: `v7.2.16`
**ng-lightning**: `v4.8.2`
**LDS**: `v2.8.3`
**Browser**: Chrome 81.0.4044.129

**Comment by bekos** [comment]
@gagan-lokesh Your ng-ligthning version is too old. Please upgrade to latest version and try again. Unfortunately I don't have enough time to support patches on older versions.
