### ISSUE TITLE
Docs site issues

### ISSUE THREAD

**Issue by missmatsuko** [ng-lightning/ng-lightning#513]
- Homepage says the current release is 5.0.0, but it should be 6.0.0. Probably a rebuild will fix this.

- Shield logo at top left is missing its background image.

<img width="248" alt="Screenshot of the " src="https://user-images.githubusercontent.com/17884198/81855056-a1d17f00-9513-11ea-9078-eea8591eb252.png">

Maybe the asset for the background image was moved? I have an error in the console `shield.svg:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

- Also, no need for assistive text in that link because that text is duplicated:

```
<a class="slds-text-link_reset" routerlink="/" href="#/">
  <div class="header__logo"></div>
  <span class="slds-assistive-text">ng-lightning</span>
  <div class="header__title">NG-LIGHTNING</div>
</a>
```

- Link to Comboboxes at the bottom of the [Picklist](http://ng-lightning.github.io/ng-lightning/#/components/picklist) and [Lookups](http://ng-lightning.github.io/ng-lightning/#/components/lookups) are broken

**Comment by bekos** [comment]
Released v6.1.0. @missmatsuko Thx for your contributions.
