### ISSUE TITLE
for not made components

### ISSUE THREAD

**Issue by colinshen** [ng-lightning/ng-lightning#83]
If the components are not made yet. What should I do? Just use the original library? I know this is a stupid question, but could you give me some suggestions for my project now?

**Comment by bekos** [comment]
Hi @colinshen. Thanks for using ng-lightning :-) 

Can you give me an example of the components you are looking for? Also, which is the _original library_ that you mention?

**Comment by colinshen** [comment]
Sorry about unclear question. Originial library I said is [lightning design system](https://www.lightningdesignsystem.com/). 
For components, such as Datekickers, Tree, Card, table componsts. What I meant was If I only use them to show data or bind some easy actions, should I just use the style directly from Ligntning Design System?

**Comment by bekos** [comment]
@colinshen Yes that's right :) Just use the HTML markup and CSS from Lightning and just hook in there your custom logic with Angular 2. 

BTW there is already some work started for most of the components you mentioned.
