### ISSUE TITLE
Problems with rxJs

### ISSUE THREAD

**Issue by alapasset** [ng-lightning/ng-lightning#88]
Hello,

I joined your module to display a modal , but I have a concern with your version of angular and RxJS I think. I have the following error:

```
/node_modules/ng-lightning/pick/pick.d.ts:2:33 
Cannot find module 'rxjs/subject/BehaviorSubject'.
```

Thx.

**Comment by bekos** [comment]
@alapasset Can you try the just released 0.8.0 and report back if this fixes your issues?

**Comment by alapasset** [comment]
The rxJs probleme seems to be resolved now i have DI Exception ;)

**Comment by bekos** [comment]
Nice 👍
